### ISSUE TITLE
** (UndefinedFunctionError) function Rummage.Ecto.__using__/1 is undefined or private

### ISSUE THREAD

**Issue by shivno** [aditya7iyengar/rummage_ecto#47]
i use rummage_ecto 1.2.0, when downgrading to 1.0.0 it works.
offending line is just "use Rummage.Ecto"

also, i get a warning when compiling:

warning: the dependency :rummage_phoenix requires Elixir "~> 1.3.4" but you are running on v1.4.2
but probably this doesnt work because of the v, as 1.4.2 is greater than 1.3.4
os is freebsd if that matters
thanks

**Comment by shayrm** [comment]
Hello guys,
I have the same error when trying to use rummage_ecto 1.2.0.
I could not downgrade to 1.0.0 since there is no support in different @primary_key 
As described in [issue 45](https://github.com/aditya7iyengar/rummage_ecto/issues/45)
Is there a workaround which I could use pagination for table without id field and Elixir > 1.3.4 ?

Thanks!

**Comment by aditya7iyengar** [comment]
#56 Hey @shivno and @shayrm, I will be addressing those issues on this PR.

**Comment by aditya7iyengar** [comment]
Addressed in #56
